# general
#seed: 24
workers: 0

# train options
batch_size: 512 # original set to 256

start_epoch: 1
epochs: 300
classnum: 10
# model options
feature_dim: 128
model_path: "save/sc-ms-loss-PBMC-Pos2-Neg10"
reload: False
num_genes: 2000

# loss options
learning_rate: 0.00003 # original set to 3e-4

MULTI_SIMILARITY_LOSS_SCALE_POS: 2.0
MULTI_SIMILARITY_LOSS_SCALE_NEG: 10.0
NN_COUNT : 10
MAX_ELEMENTS: 93661