# general
#seed: 24
workers: 0

# train options
batch_size: 512 # original set to 256

start_epoch: 1
epochs: 300
classnum: 14
# model options
feature_dim: 128
model_path: "save/sc-ms-loss"
reload: False
num_genes: 2000

# loss options
learning_rate: 0.00003 # original set to 3e-4
weight_decay: 0.
instance_temperature: 0.5 # original 0.5
cluster_temperature: 0.5 # original 0.5

# 和数据关系很大，就得自己调试
MULTI_SIMILARITY_LOSS_SCALE_POS: 2.0
MULTI_SIMILARITY_LOSS_SCALE_NEG: 40.0
NN_COUNT : 10