# general
#seed: 24
workers: 0

# train options
batch_size: 1024 # original set to 256
start_epoch: 1
epochs: 500
classnum: 14
# model options
feature_dim: 128
model_path: "save/sc-no-bank-highvar-500-sctransformation"
reload: False
num_genes: 2000

# loss options
learning_rate: 0.00003 # original set to 3e-4
weight_decay: 0.
instance_temperature: 0.2 # original 0.5
cluster_temperature: 0.2 # original 0.5
